### ISSUE TITLE
Drag & Drop fails

### ISSUE THREAD

**Issue by beppe9000** [Aluxian/Whatsie#57] opened 2016-04-14 12:37 UTC
D&D fails when dropping a picture on the window, opening it as a page

**Comment by Aluxian** [comment] 2016-04-14 13:02
I fixed this, I'll be released in the next version.

--
Alexandru Rosianu Full-Stack Developer aluxian.com | startersquad.com On Thu, Apr 14, 2016 at 3:37 PM, beppe9000 < notifications@github.com [notifications@github.com] > wrote:
D&D fails when dropping a picture on the window, opening it as a page

**Comment by Aluxian** [comment] 2016-04-14 13:19
Also, duplicate of this: https://github.com/Aluxian/Whatsie/issues/37

**Closed by Aluxian** 2016-04-14 13:19 UTC
Labels: bug, duplicate

**Comment by beppe9000** [comment] 2016-04-14 15:37
ookk
